---
#
#  Gitlab KVM: Gitlab EE and Gitlab Runner
#

- name: Deploy and configure KVM
  hosts: gitlab
  gather_facts: false
  pre_tasks:
  - name: create kvm
    include_role:
      name: common
      tasks_from: create_kvm.yml
  - name: gather KVM facts
    gather_facts:
  roles:
  - docker
  - docker_gitlab 
