---
#
# roles/kanban/tasks/kanban_install.yml
#

- name: Install APT key for kanban
  become: true
  apt_key:
    url: https://dl.packager.io/srv/opf/openproject/key

- name: Install repo for kanban controller
  become: true
  get_url:
    url: https://dl.packager.io/srv/opf/openproject/stable/12/installer/ubuntu/20.04.repo
    dest: /etc/apt/sources.list.d/openproject.list
    owner: root
    group: root

- name: update apt cache and install required packages
  become: true
  apt: 
    name: '{{ kanban_apt_packages }}'
    state: present
    update_cache: yes


# - name: create backup directory
#   file:
#     path: '{{ item }}'
#     state: directory
#     mode: 0700
#     owner: '{{ kanban_user }}'
#     group: '{{ kanban_group }}'
#   with_items:
#     - '{{ all_backup_root }}' 
#     - '{{ kanban_backup_dir }}' 
#   become: true

# - name: mount backup share
#   include_role:
#     name: common
#     tasks_from: mount_share
#   vars:
#     mount_src:  '{{ all_nas_backup }}'
#     mount_dest: '{{ all_backup_root }}'
#     mount_username: '{{ kanban_service_username }}'
#     mount_password: '{{ kanban_service_password }}'
#     mount_uid: '{{ kanban_user }}'
#     mount_gid: '{{ kanban_group }}'
#     mount_options: ',file_mode=0770,dir_mode=0770,nounix'
#   no_log: true

# - name: copy backup script
#   template:
#     src: backup_kanban.sh.j2
#     dest: /usr/local/bin/backup_kanban.sh
#     mode: 'a+x'
#   become: true

# - name: setup backup cronjob
#   cron:
#     name: 'Backup kanban'
#     job: '/usr/local/bin/backup_kanban.sh'
#     user: root
#     cron_file: backup_kanban
#     hour: '3'
#     minute: '5'
#   become: true

# - name: configure backup rotation
#   include_role:
#     name: common
#     tasks_from: rotate_backups
#   vars:
#     - cron_user: root
#     - backup_path: '{{ kanban_backup_dir }}'
