---
#
# roles/docker_tasks/defaults/main.yml
#

docker_tasks_required_vars:
  - docker_uid
  - docker_gid
  - docker_tasks_database_pw
  - docker_tasks_database_root_pw
docker_tasks_docker_builds: '{{ all_docker_builds }}'
docker_tasks_docker_storage: '{{ all_docker_storage }}'
