---
#
# roles/docker_kanban/tasks/main.yml
#


- name: create compose directory
  become: true
  file:
    path: '{{ docker_kanban_docker_builds }}/kanban'
    state: directory
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
    mode: 0700

- name: copy docker files
  become: true
  template:
    src: '{{ item }}.j2' 
    dest: '{{ docker_kanban_docker_builds }}/kanban/{{ item }}'
    backup: true
    owner: '{{ docker_uid }}'
    group: '{{ docker_gid }}'
    mode: 0700
  loop:
    - docker-compose.yml

- name: configure backup rotation
  include_role:
    name: common
    tasks_from: rotate_backups
  vars:
    - cron_user: root
    - backup_path: '{{ docker_kanban_docker_storage }}/volume_backups'