---
#
# roles/plex/tasks/main.yml
#


- name: check required variables
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  loop: '{{ plex_required_vars }}'

- name: load plex install tasks
  include_tasks: plex_install.yml